### ISSUE TITLE
image_default() does not work

### ISSUE THREAD

**Issue by lrineau** [CGAL/cgal-testsuite-dockerfiles#1]
I have the image `gal-testsuite/archlinux`. It is tagged `latest` implicitly by Docker, but that tag does not seem to be implicit when one query images:

```
$ docker images cgal-testsuite/archlinux:latest
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE

$ docker images cgal-testsuite/archlinux       
REPOSITORY                 TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
cgal-testsuite/archlinux   latest              d2201388444f        40 minutes ago      1.376 GB
```

As a consequence, the function `image_default()` (which should be named `images_default()` actually) does not work:
```
$ ./test_cgal.py 
Could not find image: cgal-testsuite/archlinux:latest
Traceback (most recent call last):
  File "/home/lrineau/Git/CGAL-testsuite-dockerfiles/test_cgal.py", line 202, in <module>
    main()
  File "/home/lrineau/Git/CGAL-testsuite-dockerfiles/test_cgal.py", line 152, in main
    assert do_images_exist(args.images), 'Specified images could not be found.'
AssertionError: Specified images could not be found.
zsh: exit 1     ~/Git/CGAL-testsuite-dockerfiles/test_cgal.py
zsh: exit 1
```

**Comment by bo0ts** [comment]
This has been addressed by commit f67895c44f7aee0eb45a1db2b4ebaa1466104151
